#Development DockerFile for the client
#Image source
FROM node:alpine

#Woking directory
WORKDIR '/app'

#Copy JSON package
COPY ./package.json ./

#Run our app
RUN npm install

#Copy files
COPY . .

#Start the server
CMD ["npm", "run", "start"]